### ISSUE TITLE
desafio-m4 

### ISSUE THREAD

**Issue by heberjbaez** [leandromartin114/dwf-m4-desafio#1]
Hola Leandro! como estas? estuve revisando tu desafío y está todo muy bien. 
Quizás un pequeño detalle nada más es que yo hubiera hecho que el formulario se limpie cada vez que se envían los datos.
Pero después todo lo demás está perfecto, tanto el código que me pareció muy legible como la parte visual de la web que está muy prolija.
Un abrazo y éxitos para el siguiente modulo!

**Comment by leandromartin114** [comment]
Gracias Heber!
